# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Pull Dependencies from Repository A

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pull-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch JARs from Repository A
        run: |
          mkdir repo_a
          curl -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
               -LJO https://api.github.com/repos/fdesdin/Repository-A/actions/artifacts/repo-a-artifact/zip

          unzip -o repo-a-artifact.zip -d repo_a

      - name: Copy JARs to the desired location
        run: |
          # Customize this based on your project structure and the location where you want to copy the JARs
          cp repo_a/path/to/artifacts/*.jar .
